version : '3.8'
services:
  ng:
    depends_on:
      - wp
      - adm
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html:rw
    networks:
      - myOwnNetwork
    restart: on-failure
  wp:
    depends_on:
      - db
    build: ./requirements/wordpress
    volumes:
      - wp_data:/var/www/html:rw
    environment:
      - DB_NAME=${DB_NAME}
      - DOMAIN_NAME=${DOMAIN_NAME}
      - WP_USER=${WP_USER}
      - WP_PASSWORD=${WP_PASSWORD}
      - WP_EMAIL=${WP_EMAIL}
      - DB_PASSWORD=${DB_PASSWORD}
    networks:
      - myOwnNetwork
    restart: on-failure
  db:
    build: 
      context: ./requirements/mariadb
      args:
        - DB_NAME=${DB_NAME}
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_USER=${DB_USER}
    ports:
      - "3306:3306"
    environment:
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_USER=${DB_USER}
    networks:
      - myOwnNetwork
    volumes:
      - db_data:/var/lib/mysql
  #---------------------bonus--part
  rd:
    build: requirements/bonus/redis
    ports:
      - "6379:6379"
    networks:
      - myOwnNetwork
    restart: on-failure
  ftp:
    build: requirements/bonus/ftp
    ports:
      - "21:21"
    volumes:
      - ftp_data:/var/www/html
    networks:
      - myOwnNetwork
    restart: on-failure
  adm:
    build: requirements/bonus/adminer
    volumes:
      - adm_data:/var/www/html
    networks:
      - myOwnNetwork
  portainer:
    build: requirements/bonus/portainer
    restart: on-failure
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - 9443:9443

networks:
  myOwnNetwork:
    driver: bridge
volumes:
    wp_data:
      driver: 'local'
      driver_opts:
        type: volume
        o: 'bind'
        device: /home/aaitbelh/data/wp
    db_data:
      driver: 'local'
      driver_opts:
        type: none
        o: 'bind'
        device: /home/aaitbelh/data/mariadb
    ftp_data:
      driver_opts:
        type: volume
        o: 'bind'
        device: /home/aaitbelh/data/wp
    adm_data:
      driver: 'local'
      driver_opts:
        type: volume
        o: 'bind'
        device: /home/aaitbelh/data/wp
    portainer_data:
      driver: 'local'
      driver_opts:
        type: volume
        o: 'bind'
        device: /home/aaitbelh/data/portainer
